page_title: Calin Bule - Nova Card
description: calinbule Nova Card profile
baseurl: /
url: https://calinbule.novacard.ro
avatar: avatar.png
contact-first_name: Calin
contact-last_name: Bule
contact-title: Inginer Software
contact-company: Nova Card
contact-email: calin@novacard.ro
contact-phone: +40757846420
contact-website: https://calinbule.novacard.ro
contact-facebook_url: https://facebook.com/calin.bule
contact-linkedin_url: https://linkedin.com/in/calinbule
contact-instagram_url: https://facebook.com/calin.bule
contact-pinterest_url: https://facebook.com/calin.bule
contact-twitter_url: 
contact-youtube_url: 
contact-snapchat_url: 
contact-whatsapp_url: 
contact-tiktok_url: 
contact-telegram_url: 
contact-skype_url: 
contact-github_url: 
contact-gitlab_url: 
